try new docker build

diff --git a/frontend/ocr-chinese/Dockerfile b/frontend/ocr-chinese/Dockerfile
--- a/frontend/ocr-chinese/Dockerfile
+++ b/frontend/ocr-chinese/Dockerfile
@@ -1,36 +1,57 @@
-# Install deps
-FROM node:12 AS base
-WORKDIR /base
-COPY . .
-RUN yarn install --frozen-lockfile
-
-# Build app
-FROM base AS build
-ENV NODE_ENV=production
-WORKDIR /build
-COPY --from=base /base ./
-RUN yarn run build
-RUN yarn install --production --ignore-scripts --prefer-offline
-
-# Create production container
-FROM node:12 AS production
-ENV NODE_ENV=production
+# Install dependencies only when needed
+FROM node:16-alpine AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
-COPY --from=build /build/package.json /build/yarn.lock ./
-# Need to add dummy RUN statements so Docker doesn't crash...
-# Ref. https://github.com/moby/moby/issues/37965
-RUN true
-COPY --from=build /build/next.config.js ./
-RUN true
-COPY --from=build /build/yarn.lock ./
-RUN true
-COPY --from=build /build/.next ./.next
-RUN true
-COPY --from=build /build/public ./public
-RUN true
-COPY --from=build /build/node_modules ./node_modules
-RUN yarn cache clean
 
-# Running the app
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM node:16-alpine AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
+COPY . .
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN yarn build
+
+# If using npm comment out above and use below instead
+# RUN npm run build
+
+# Production image, copy all the files and run next
+FROM node:16-alpine AS runner
+WORKDIR /app
+
+ENV NODE_ENV production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED 1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
-CMD [ "yarn", "start" ]
+
+ENV PORT 3000
+
+CMD ["node", "server.js"]
